### PR TITLE
Fix linkage of global identifiers

### PR DESCRIPTION
**Pull request by AndreasKoelbl**
Align the code to the standard and modern compilers.

Signed-off-by: Andreas Kölbl <koelblandreas@freenet.de>

### CODE REVIEW

**Comment by dfandrich** [comment]
Looks like an alternate take on pr#13.

**Review by ecashin — CHANGES_REQUESTED** [review]
Can you please update the documentation with information about what version of gcc introduced this option and how to build differently when using an older gcc?
Sorry I am not responsive lately, but I'll try to keep an eye out for your response.

**Comment by AndreasKoelbl** [comment]
I don't know how this is information is valuable to someone reading the doc. The old code would still compile when using -fcommon as flag.

**Comment by ecashin** [comment]
When was that option first sorted in gcc? If it was long enough ago, and there's no disadvantage to using it, then you're right.
The documentation will help people understand why we use the option of they're using an old gcc out trying to use their own favorite compiler.

**Comment by AndreasKoelbl** [comment]
You are right, we should leave the compile flag out in order to avoid confusion and enhance cross-compiler-portability as -fno-common serves ANSI-C-like behaviour. I don't think the flag has more functionality behind than to make its usage obvious. The oldest reference I found was an 18 year old Changelog entry to compile gcc itself with that patch.

**Comment by ecashin** [comment]
18 years is long enough!

**Pull request merged**
